# Generated by Django 4.1.7 on 2023-03-16 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.PositiveIntegerField()),
                ('receiver_id', models.PositiveIntegerField()),
                ('reservation', models.BooleanField()),
                ('cancellation', models.BooleanField()),
                ('comment', models.BooleanField()),
                ('content', models.CharField(max_length=100)),
                ('sender_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
